// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_level_6_time = "CgkI9oaq2dELEAIQFQ"; // <GPGSID>
        public const string leaderboard_level_10_time = "CgkI9oaq2dELEAIQGQ"; // <GPGSID>
        public const string leaderboard_level_14_time = "CgkI9oaq2dELEAIQHQ"; // <GPGSID>
        public const string leaderboard_level_1_time = "CgkI9oaq2dELEAIQEA"; // <GPGSID>
        public const string leaderboard_level_5_time = "CgkI9oaq2dELEAIQFA"; // <GPGSID>
        public const string leaderboard_level_9_time = "CgkI9oaq2dELEAIQGA"; // <GPGSID>
        public const string achievement_master_of_9 = "CgkI9oaq2dELEAIQCA"; // <GPGSID>
        public const string leaderboard_level_13_time = "CgkI9oaq2dELEAIQHA"; // <GPGSID>
        public const string achievement_top_of_the_top = "CgkI9oaq2dELEAIQDw"; // <GPGSID>
        public const string leaderboard_level_4_time = "CgkI9oaq2dELEAIQEw"; // <GPGSID>
        public const string achievement_master_of_10 = "CgkI9oaq2dELEAIQCQ"; // <GPGSID>
        public const string achievement_master_of_11 = "CgkI9oaq2dELEAIQCg"; // <GPGSID>
        public const string achievement_master_of_12 = "CgkI9oaq2dELEAIQCw"; // <GPGSID>
        public const string achievement_master_of_13 = "CgkI9oaq2dELEAIQDA"; // <GPGSID>
        public const string achievement_master_of_14 = "CgkI9oaq2dELEAIQDQ"; // <GPGSID>
        public const string achievement_master_of_15 = "CgkI9oaq2dELEAIQDg"; // <GPGSID>
        public const string achievement_first_steps = "CgkI9oaq2dELEAIQAQ"; // <GPGSID>
        public const string leaderboard_level_12_time = "CgkI9oaq2dELEAIQGw"; // <GPGSID>
        public const string achievement_3_on_3 = "CgkI9oaq2dELEAIQAw"; // <GPGSID>
        public const string leaderboard_level_3_time = "CgkI9oaq2dELEAIQEg"; // <GPGSID>
        public const string leaderboard_level_7_time = "CgkI9oaq2dELEAIQFg"; // <GPGSID>
        public const string achievement_master_of_2 = "CgkI9oaq2dELEAIQAg"; // <GPGSID>
        public const string leaderboard_level_11_time = "CgkI9oaq2dELEAIQGg"; // <GPGSID>
        public const string achievement_master_of_4 = "CgkI9oaq2dELEAIQBA"; // <GPGSID>
        public const string achievement_master_of_5 = "CgkI9oaq2dELEAIQBQ"; // <GPGSID>
        public const string achievement_master_of_6 = "CgkI9oaq2dELEAIQBg"; // <GPGSID>
        public const string achievement_master_of_7 = "CgkI9oaq2dELEAIQBw"; // <GPGSID>
        public const string leaderboard_level_15_time = "CgkI9oaq2dELEAIQHg"; // <GPGSID>
        public const string leaderboard_level_2_time = "CgkI9oaq2dELEAIQEQ"; // <GPGSID>

}

